name: Find posts

on:
    push:
        branches:
            - main

jobs:
    run-node:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install dependencies
              run: npm install

            - name: Run script
              run: npm run posts

            - name: Upload output
              uses: actions/upload-artifact@v2
              with:
                  name: posts-file
                  path: posts.json

    commit-file:
        needs: run-node
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Download output
              uses: actions/download-artifact@v2
              with:
                  name: posts-file
                  path: .

            - name: Commit to repo
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add posts.json
                  git commit -m "Add posts JSON"
                  git push
